#[derive(Debug, Clone, PartialEq)]
pub enum AppAction {
    InsertChar(char),
    InsertStr(String),
    InsertFraction,
    InsertSqrt,
    Backspace,
    MoveCursorLeft,
    MoveCursorRight,
    MoveCursorHome,
    MoveCursorEnd,
    ScrollUp,
    ScrollDown,
    Evaluate,
    ClearInput,
    AllClear,
    StoreVariable(char),
    InsertVariable(char),
    ToggleAngleUnit,
    OpenHelp,
    CloseHelp,
    Warn(String),
    Quit,
    ClickAt(u16, u16),
}
